apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '20'
  creationTimestamp: '2021-04-30T08:10:25Z'
  generation: 25
  labels:
    app: demo-default
  name: demo-default
  namespace: default
  resourceVersion: '1334591115'
  selfLink: /apis/apps/v1/namespaces/default/deployments/demo-default
  uid: 8203596a-d772-457f-bf9f-e69f496a736e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-default
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1620219501508'
      labels:
        app: demo-default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: priorityLevel
                    operator: In
                    values:
                      - Medium
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: 'http://+:80'
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: 'true'
          image: 'registry-vpc.cn-hangzhou.aliyuncs.com/ql361/demo:202105111114'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: demo-default
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 256Mi
            requests:
              cpu: 100m
              ephemeral-storage: 2Gi
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: jasperreport
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2021-04-30T08:10:25Z'
      lastUpdateTime: '2021-05-11T03:15:34Z'
      message: ReplicaSet "demo-default-5c7678f84c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2021-05-11T07:55:02Z'
      lastUpdateTime: '2021-05-11T07:55:02Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 25
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
